version: '3.8'  # Optional; you can remove it if deprecated
services:
  site1:
    build:
      context: ./site1
    ports:
      - "5173:4173"  # Maps container port 4173 to host port 5173
    command: npm run preview -- --host 0.0.0.0

  site2:
    build:
      context: ./site2
    ports:
      - "5174:4174"  # Maps container port 4174 to host port 5174
    command: npm run preview -- --host 0.0.0.0
